=== ProjektAdLer/TransferFileFormat/v0.4 RoomTemplates/schema0_4.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "fileVersion": {
      "type": "string"
    },
    "amgVersion": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "language": {
      "type": "string",
      "enum": ["de", "en"]
    },
    "world": {
      "type": "object",
      "properties": {
        "lmsElementIdentifier": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "value": {
              "type": "string"
            }
          },
          "required": ["type", "value"]
        },
        "worldName": {
          "type": "string"
        },
        "worldDescription": {
          "type": "string"
        },
        "worldGoals": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "topics": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "topicId": {
                "type": "integer"
              },
              "topicName": {
                "type": "string"
              },
              "topicContents": {
                "type": "array",
                "items": {
                  "type": "integer"
                }
              }
            },
            "required": ["topicId", "topicName", "topicContents"]
          }
        },
        "spaces": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "spaceId": {
                "type": "integer"
              },
              "lmsElementIdentifier": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                },
                "required": ["type", "value"]
              },
              "spaceName": {
                "type": "string"
              },
              "spaceDescription": {
                "type": "string"
              },
              "spaceGoals": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "spaceSlotContents": {
                "type": "array",
                "items": {
                  "oneOf": [
                    {
                      "type": "integer"
                    },
                    {
                      "type": "null"
                    }
                  ]
                },
                "minItems": 1
              },

              "requiredPointsToComplete": {
                "type": "integer"
              },
              "requiredSpacesToEnter": {
                "type": "string"
              },
              "roomTemplate": {
                "type": "string"
              },
              "roomTemplateStyle": {
                "type": "string"
              }
            },
            "required": [
              "spaceId",
              "lmsElementIdentifier",
              "spaceDescription",
              "spaceGoals",
              "spaceSlotContents",
              "requiredSpacesToEnter",
              "spaceName",
              "roomTemplate",
              "roomTemplateStyle"
            ]
          },
          "minItems": 1
        },
        "elements": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "elementId": {
                "type": "integer"
              },
              "lmsElementIdentifier": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  }
                },
                "required": ["type", "value"]
              },
              "elementName": {
                "type": "string"
              },
              "elementDescription": {
                "type": "string"
              },
              "elementGoals": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "elementCategory": {
                "type": "string"
              },
              "elementFileType": {
                "type": "string"
              },
              "elementMaxScore": {
                "type": "integer"
              },
              "elementModel": {
                "type": "string"
              }
            },
            "required": [
              "elementId",
              "lmsElementIdentifier",
              "elementCategory",
              "elementFileType",
              "elementMaxScore",
              "elementName",
              "elementModel"
            ],
            "minItems": 1
          }
        }
      },
      "required": ["lmsElementIdentifier", "spaces", "elements", "worldName"]
    }
  },
  "required": ["fileVersion", "world"]
}

=== ProjektAdLer/TransferFileFormat/v0.4 RoomTemplates/AdLerWorldTransfer0_4.json
{
  "fileVersion": "0.4",
  "amgVersion": "1.0",
  "author": "Peter",
  "language": "de",
  "world": {
    "lmsElementIdentifier": {
      "type": "idNumber",
      "value": "123456789randomID"
    },
    "worldName": "Name der Welt",
    "worldDescription": "Beschreibung der Welt",
    "worldGoals": ["Ziel 1", "Ziel 2"],
    "topics": [
      {
        "topicId": 1,
        "topicName": "A",
        "topicContents": [1, 2]
      }
    ],
    "spaces": [
      {
        "spaceId": 1,
        "lmsElementIdentifier": {
          "type": "idNumber",
          "value": "123456789randomID"
        },
        "spaceName": "Name des Lernraums",
        "spaceDescription": "Beschreibung des Lernraums",
        "spaceGoals": ["Ziel 1", "Ziel 2"],
        "spaceSlotContents": [1, null, 2, 3, null, null],
        "requiredPointsToComplete": 100,
        "requiredSpacesToEnter": "(5)v((7)^(4))",
        "roomTemplate": "rectangle2x3",
        "roomTemplateStyle": "casino"
      }
    ],
    "elements": [
      {
        "elementId": 1,
        "lmsElementIdentifier": {
          "type": "moduleName",
          "value": "Ein wunderschöner, für den Nutzer sichtbarer, String"
        },
        "elementName": "Name des Elements",
        "elementDescription": "Beschreibung des Lernelements",
        "elementGoals": ["Ziel 1", "Ziel 2"],
        "elementCategory": "image",
        "elementFileType": "image:png",
        "elementMaxScore": 123,
        "elementModel": "ArcadeMachine"
      }
    ]
  }
}
